- name: retun secrets as dict
  ansible.builtin.set_fact: 
    components_secrets: "{{ lookup('community.hashi_vault.hashi_vault', 'roboshop-{{ env }}/data/{{ component_name }} token={{ vault_token }} url=http://vault-private.kommanuthala.store:8200') }}"

- name: Copy systemd service file
  ansible.builtin.template:
    src: component.service  
    dest: /etc/systemd/system/{{ component_name }}.service

- name: Start service
  ansible.builtin.systemd_service:
    name: "{{ component_name }}"
    state: restarted
    enabled: yes
    daemon_reload: yes